### ISSUE TITLE
ES5 compatibility

### ISSUE THREAD

**Issue by fgrandval** [YuriGor/deepdash#28]
Hi,
I'm having an issue when building and running on IE11, a project using deepdash 4.2.10.
The error comes from [getHasChildren.js](https://github.com/YuriGor/deepdash/blob/master/private/getHasChildren.js#L5) which use an arrow function and cause a 'SCRIPT1002' error in Internet Explorer 11.

Can you fix this issue ?
Thank you !

**Comment by YuriGor** [comment]
Hi, yes, thank you for report, will fix tomorrow
I should also check my eslint settings and run eslint before commit.

**Comment by YuriGor** [comment]
fixed in v4.2.11

**Comment by fgrandval** [comment]
Thank you !!

**Comment by fgrandval** [comment]
Hi @YuriGor, 
4.2.11 didn't fix my issue, the problem persists :

![Image of arrow error in IE](https://i.imgur.com/OsoG3Nz.png)

![Image of arrow error in IE](https://i.imgur.com/NtA8fd7.png)

**Comment by YuriGor** [comment]
Do you use browser build? Latest version?
There is no arrow function anymore:
https://github.com/YuriGor/deepdash/blob/8343e3c1101a444d30157f4457012d11b765b45f/browser/deepdash.js#L56

**Comment by YuriGor** [comment]
check if you npm/yarn really upgraded a package if you use it,
or make sure you use correct [link to CDN ](https://cdn.jsdelivr.net/npm/deepdash@4.2.11/browser/deepdash.js)
also clear browser's cache.

**Comment by fgrandval** [comment]
I'm importing mapDeep method as standalone ES6 module
`import mapDeep from 'deepdash/mapDeep';`

**Comment by YuriGor** [comment]
So you probably need to use babel/bable webpack plugin to make the code compatible with browsers.

**Comment by fgrandval** [comment]
[PR 30](https://github.com/YuriGor/deepdash/pull/30) solves the problem

**Comment by YuriGor** [comment]
No actually, this pr tries to change generated code, and there are several places where es6 used, so all the code need to be changed.

I'll think about to come back to es5 in the sources so no translation will be needed, but this will be not so fast.
So please consider to use transpiler for now.

**Comment by YuriGor** [comment]
@fgrandval I pushed another version with transpiled commonjs build,
now it should work for your case.

**Comment by fgrandval** [comment]
It works now ! Thank you @YuriGor

**Comment by YuriGor** [comment]
Thank you for feedback, @fgrandval, consider to put a star to github project - it will promote the package in npm search :star2:
